(function() {var implementors = {
"bevy":[],
"bevy_animation":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_animation/struct.AnimationClip.html\" title=\"struct bevy_animation::AnimationClip\">AnimationClip</a>"]],
"bevy_asset":[],
"bevy_asset_loader":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_asset_loader/standard_dynamic_asset/struct.StandardDynamicAssetCollection.html\" title=\"struct bevy_asset_loader::standard_dynamic_asset::StandardDynamicAssetCollection\">StandardDynamicAssetCollection</a>"]],
"bevy_audio":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_audio/struct.Pitch.html\" title=\"struct bevy_audio::Pitch\">Pitch</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_audio/struct.AudioSource.html\" title=\"struct bevy_audio::AudioSource\">AudioSource</a>"]],
"bevy_ecs_ldtk":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_ecs_ldtk/assets/struct.LdtkProject.html\" title=\"struct bevy_ecs_ldtk::assets::LdtkProject\">LdtkProject</a>"]],
"bevy_ecs_tilemap":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_ecs_tilemap/prelude/struct.StandardTilemapMaterial.html\" title=\"struct bevy_ecs_tilemap::prelude::StandardTilemapMaterial\">StandardTilemapMaterial</a>"]],
"bevy_fluent":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_fluent/struct.ResourceAsset.html\" title=\"struct bevy_fluent::ResourceAsset\">ResourceAsset</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_fluent/struct.BundleAsset.html\" title=\"struct bevy_fluent::BundleAsset\">BundleAsset</a>"]],
"bevy_internal":[],
"bevy_render":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/render_resource/struct.Shader.html\" title=\"struct bevy_render::render_resource::Shader\">Shader</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/mesh/skinning/struct.SkinnedMeshInverseBindposes.html\" title=\"struct bevy_render::mesh::skinning::SkinnedMeshInverseBindposes\">SkinnedMeshInverseBindposes</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/mesh/struct.Mesh.html\" title=\"struct bevy_render::mesh::Mesh\">Mesh</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_render/texture/struct.Image.html\" title=\"struct bevy_render::texture::Image\">Image</a>"]],
"bevy_scene":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_scene/struct.Scene.html\" title=\"struct bevy_scene::Scene\">Scene</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_scene/struct.DynamicScene.html\" title=\"struct bevy_scene::DynamicScene\">DynamicScene</a>"]],
"bevy_sprite":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_sprite/struct.ColorMaterial.html\" title=\"struct bevy_sprite::ColorMaterial\">ColorMaterial</a>"],["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_sprite/struct.TextureAtlas.html\" title=\"struct bevy_sprite::TextureAtlas\">TextureAtlas</a>"]],
"bevy_text":[["impl <a class=\"trait\" href=\"bevy_asset/trait.Asset.html\" title=\"trait bevy_asset::Asset\">Asset</a> for <a class=\"struct\" href=\"bevy_text/struct.Font.html\" title=\"struct bevy_text::Font\">Font</a>"]],
"theseeker_engine":[["impl <a class=\"trait\" href=\"theseeker_engine/prelude/trait.Asset.html\" title=\"trait theseeker_engine::prelude::Asset\">Asset</a> for <a class=\"struct\" href=\"theseeker_engine/assets/script/struct.Script.html\" title=\"struct theseeker_engine::assets::script::Script\">Script</a>"],["impl <a class=\"trait\" href=\"theseeker_engine/prelude/trait.Asset.html\" title=\"trait theseeker_engine::prelude::Asset\">Asset</a> for <a class=\"struct\" href=\"theseeker_engine/assets/animation/struct.SpriteAnimation.html\" title=\"struct theseeker_engine::assets::animation::SpriteAnimation\">SpriteAnimation</a>"]],
"theseeker_game":[["impl <a class=\"trait\" href=\"theseeker_game/prelude/trait.Asset.html\" title=\"trait theseeker_game::prelude::Asset\">Asset</a> for <a class=\"struct\" href=\"theseeker_game/graphics/fog/struct.FogMaterial.html\" title=\"struct theseeker_game::graphics::fog::FogMaterial\">FogMaterial</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()